defaults:
    -
        scope:
            path: ''
            collection: 'resources'
        values:
            layout: 'article'
            image: '/assets/img/fb-link.png'

exclude:
    - 'CONTRIBUTING.md'
    - 'Gemfile'
    - 'LICENSE'
    - 'README.md'
    - 'build.php'
    - '_resources/README.md'
    - '_resources/LICENSE'
    - '_resources/CONTRIBUTING.md'
    - 'conduct/README.md'

collections:
    resources:
        output: true
        output_ext: html
        permalink: /:path/

fb-group-id: 2204685680

# Jekyll SEO Tag Plugin
title: 'World Wide PHP Facebook Group'
description: 'World Wide PHP Facebook Group'
logo: '/assets/img/fb-link.png'

gems:
    - 'jekyll-sitemap'
    - 'jekyll-redirect-from'
    - 'jekyll-seo-tag'
