defaults:
    -
        scope:
            path: ""
        values:
            read_time: "1 min"
            updated: "september 18, 2014"
    -
        scope:
            path: ""
            collection: "faq"
        values:
            layout: standalone-faq-entry
            og_image: "assets/img/php-faq.png"

exclude: [ 'Gemfile', 'README.md', 'LICENSE', '_faq/README.md', '_faq/LICENSE', '_faq/CONTRIBUTING.md' ]

admins:

    -
        name: "Peter Kokot"
        profile-id: "peterkokot"

    -
        name: "Tony Sodano"
        profile-id: "tony.sodano.12"

    -
        name: "Asad Hasan"
        profile-id: "asadg"

    -
        name: "Ahsan Ali"
        profile-id: "100000064018416"

    -
        name: "Aasif Saifuddin Auvi"
        profile-id: "asifsaif90"

    -
        name: "Matthias Kaschubowski"
        profile-id: "matthias.kaschubowski"

    -
        name: "Sami Khan"
        profile-id: "samikjr"

    -
        name: "Mansoor Ahmed"
        profile-id: "MansoorA"


collections:
    faq:
        output: true
        output_ext: html
        permalink: /faq/:path/

fb-group-id: 2204685680
