defaults:
    -
        scope:
            path: ""
        values:
            read_time: "1 min"
            updated: "september 18, 2014"
    -
        scope:
            path: ""
            collection: "resources"
        values:
            layout: "article"
            og_image: "assets/img/fb-link.png"
            group: "general"

exclude:
    - "CONTRIBUTING.md"
    - "Gemfile"
    - "LICENSE"
    - "README.md"
    - "faq-facebook-document.html"
    - "build.php"
    - "_resources/README.md"
    - "_resources/LICENSE"
    - "_resources/CONTRIBUTING.md"
    - "conduct/README.md"

collections:
    resources:
        output: true
        output_ext: html
        permalink: /:path/

fb-group-id: 2204685680

gems:
    - 'jekyll-sitemap'
    - 'jekyll-redirect-from'

highlighter: rouge
