defaults:
    -
        scope:
            path: ""
        values:
            read_time: "1 min"
            updated: "september 18, 2014"
    -
        scope:
            path: ""
            collection: "faq"
        values:
            layout: standalone-faq-entry
            og_image: "assets/img/php-faq-large.png"
            group: "general"

exclude: [ 'Gemfile', 'README.md', 'LICENSE', '_faq/_template.md', '_faq/README.md', '_faq/LICENSE', '_faq/CONTRIBUTING.md' ]

admins:

    -
        name: "Peter Kokot"
        profile-id: "peterkokot"
        active: true

    -
        name: "Tony Sodano"
        profile-id: "tony.sodano.12"
        active: true

    -
        name: "Asad Hasan"
        profile-id: "asadg"
        active: true

    -
        name: "Ahsan Ali"
        profile-id: "100000064018416"
        active: true

    -
        name: "Aasif Saifuddin Auvi"
        profile-id: "asifsaif90"
        active: false

    -
        name: "Matthias Kaschubowski"
        profile-id: "matthias.kaschubowski"
        active: true

    -
        name: "Sami Khan"
        profile-id: "samikjr"
        active: true

    -
        name: "Mansoor Ahmed"
        profile-id: "MansoorA"
        active: true

    -
        name: "Suraj Kumar Adhikari"
        profile-id: "surajadhikaridev"
        active: true


collections:
    faq:
        output: true
        output_ext: html
        permalink: /faq/:path/

fb-group-id: 2204685680

gems:
    - jekyll-sitemap

markdown: redcarpet

# groups of FAQs
groups:

    -
        slug: "intro"
        title: "Introduction to PHP"

    -
        slug: "community"
        title: "PHP Community"

    -
        slug: "databases"
        title: "Databases and PHP"

    -
        slug: "oop"
        title: "Object oriented programming"

    -
        slug: "security"
        title: "Security and PHP"

    -
        slug: "testing"
        title: "Testing"

    -
        slug: "general"
        title: "General PHP questions"

    -
        slug: "wwphpfb"
        title: "WW PHP FB"

