defaults:
    -
        scope:
            path: ""
        values:
            read_time: "1 min"
            updated: "september 18, 2014"
    -
        scope:
            path: ""
            collection: "faq"
        values:
            layout: standalone-faq-entry
            og_image: "assets/img/php-faq-large.png"
            group: "general"

exclude: [ 'Gemfile', 'README.md', 'LICENSE', '_faq/_template.md', '_faq/README.md', '_faq/LICENSE', '_faq/CONTRIBUTING.md' ]

collections:
    faq:
        output: true
        output_ext: html
        permalink: /faq/:path/

fb-group-id: 2204685680

gems:
    - jekyll-sitemap

markdown: redcarpet

# groups of FAQs
groups:

    -
        slug: "intro"
        title: "Introduction to PHP"

    -
        slug: "community"
        title: "PHP Community"

    -
        slug: "databases"
        title: "Databases and PHP"

    -
        slug: "oop"
        title: "Object oriented programming"

    -
        slug: "security"
        title: "Security and PHP"

    -
        slug: "testing"
        title: "Testing"

    -
        slug: "general"
        title: "General PHP questions"

    -
        slug: "wwphpfb"
        title: "WW PHP FB"
