defaults:
    -
        scope:
            path: ""
        values:
            read_time: "1 min"
            updated: "september 18, 2014"
    -
        scope:
            path: ""
            collection: "resources"
        values:
            layout: standalone-faq-entry
            og_image: "assets/img/fb-link.png"
            group: "general"

exclude:
    - "Gemfile"
    - "README.md"
    - "LICENSE"
    - "_resources/articles/_template.md"
    - "_resources/faq/_template.md"
    - "_resources/tutorials/_template.md"
    - "_resources/README.md"
    - "_resources/LICENSE"
    - "_resources/CONTRIBUTING.md"
    - "_resources/generator.php"
    - "_resources/groups.yml"

collections:
    resources:
        output: true
        output_ext: html
        permalink: /faq/:path/

fb-group-id: 2204685680

gems:
    - 'jekyll-sitemap'
    - 'jemoji'

markdown: redcarpet
redcarpet:
    extensions: ["no_intra_emphasis", "fenced_code_blocks", "autolink", "tables", "with_toc_data"]