defaults:
    -
        scope:
            path: ""
        values:
            author: "a 2 inch sized lemming"
            
    -
        scope:
            path: ""
            collection: "faq"
        values:
            layout: standalone-faq-entry

exclude: [ 'README.md', 'LICENSE', '_faq/README.md', '_faq/LICENSE' ]

fb-group-id: 2204685680

collections:
    faq:
        output: true
        output_ext: html
        permalink: /faq/:path/